name: Stuff

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Dump some environment info
      run: |
        id
        env | sort
        cat ${GITHUB_EVENT_PATH}
        sudo mount
        ls -l /opt/hostedtoolcache
        ls -l /home/runner/work/_temp
        ls -l
    - name: Try to mess with other steps
      run: |
        echo "hi" > ${GITHUB_EVENT_PATH}
        cat ${GITHUB_EVENT_PATH}
    - name: Did it work?
      run: |
        cat ${GITHUB_EVENT_PATH}
