name: CI

on: [create, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        env | sort
        echo Add other actions to build,
        echo test, and deploy your project.
        cat ${GITHUB_EVENT_PATH}
    - name: Try to mess with other steps
      run: |
        echo "hi" > ${GITHUB_EVENT_PATH}
    - name: Did it work?
      run: |
        cat ${GITHUB_EVENT_PATH}
