on: [repository_dispatch]

name: "pipelinename ${{ github.event.client_payload.jobid }}"

jobs:
  jobone:
    runs-on: ubuntu-latest
    name: "jobname ${{ github.event.client_payload.jobid }}"

    steps:
    - name: Run stuff
      run: |
        env | sort
        cat ${GITHUB_EVENT_PATH}
