on: [repository_dispatch]

jobs:
  jobone:
    runs-on: ubuntu-latest
    name: "{{ github.event.client_payload.jobid }}"

    steps:
    - name: Run stuff
      run: |
        env | sort
        cat ${GITHUB_EVENT_PATH}
