on: [repository_dispatch]

jobs:
  "jobid ${{ github.event.client_payload.jobid }}":
    runs-on: ubuntu-latest
    name: "jobname ${{ github.event.client_payload.jobid }}"

    steps:
    - name: Run stuff
      run: |
        env | sort
        cat ${GITHUB_EVENT_PATH}
